# Rosalid
# Bioinformatics Stronghold
# ID: REVC


# Given: A DNA string s of length at most 1000 bp.

# Return: The reverse complement sc of s.

s = "GGTGCAATTGTCGCGGATGGCCGTTTCGCCCCGTAGTCGTCCTGGCCCGCCAAAAAGTGTCCACCATGGTAGACACGGTGCGGGGGGTTTAATTAATGAACTGATAAGTTACGTGCACCCCAGTGTTCAAGAGAGTCCGAAAGGTATGCTAAGCGTTGTTCTGAGCGGAATATCAACTAAAGACAGTGCTTACACTTCAAGCTCTTAAATAACCAGCATTATCAGTGAACCATTGTGTGCCCTATCTATCTCGTAACTTACTTTGCACTCCCCTCGAGGGTCCGACAGATCATTAGATATGCTAGTGATGATCGTACATTTGGCCTAGTCAAGTATGGGATCACAGTACAACTCCGGGCGTCTAGAACCGAGTAAGACGGCCCAAAAATTGCGGGTTTTTGTGACCTATTCCACGCTTTCGTTAAGGAAGGTACGAAGAAAAACGATAAAAAGCCTTCAGCTTGCTGCTAGTGGGTAAACGTGATTTTCGGTCATCCCACGGATCTTTAAAGCTGCAACCATGAGGTGCAGCCACATGAGACGTCAGTTTAAGAGTTGTAAGTCGCACCACTGCGCACTTGAGGTAGCTATTATTCCCCGCTCCTTGTTTAAGTCGACCGTAATCAAAAAATATCATCTGTCGGCCCCGTAAACTGTCGTACTACTTCTTTGAATGGCTTTAGAGCAGGTCCGTTGGCACTATAGATGAAAATCGTGTCTGGAGAACGAACTCCCGTCTGACACCCGATCTGGTCATTAGGGGGAGGATTTCCTAACGCTACTGACGTTGTTTTGCCGGGTCGGTTCGGTTATGCCCGACGTGTCAGTGATCATGAGCAAACTCAACCCAGCTTCGCCCCAAATCGGTGCGGGCCAGGCGGGCGGAGGGTGGTGTCCTGTTAATTTCCAGATTATCTAAGATCGAGACGGTTATCTCCGTAATTAGTGTGGCCCGTCGGGACCTGGAGAAGTTACATAGAAAATTTACTAACC"


def complement(dna):

    sc = ""

    comp = {"A":"T", "T":"A", "C":"G", "G":"C"}
    for base in dna.upper():
        sc = comp[base] + sc

    return sc


print(complement(s))
