# Rosalid
# Bioinformatics Stronghold
# ID: RNA


# Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.

# Given: A DNA string t having length at most 1000 nt.

# Return: The transcribed RNA string of t.



# Set DNA variable
t = "ACCCCGGTGTCTGGAGATTACCACGTGTTAGCGAAATCACAGTGTAGTATCCTCCCTAGTTGGTCGACTTTAGGAACGTGACAGTCTCAATTCGGCCGGGTAACTAGTTCGACTGTCGCTTATAGTTGATGTGCGTAACTACCGGATCTCCCTACGGTGACGTCGAAATACATAGCCGCCACAGTAGGGCCAAAACGGCGAAAACTTGCGTGAATAGACGCCCGGCAATGAAACCTAAGTTCGAGAGCCGCAAACGTCTACGTTGGACATAGGCGCTCCACTCCTAAACTATGCAGCGTATCTAAAAAGTAAGTTGACCGTTTACAAGGATTCGCGTGGGGTGAAAACGCCGCATGCCGCACCCATGAGGGTCAGAGATAGGGTCCAGCGCGCAAGTGCTTTACTTAATTCCAGATCCCTGGCTGATGACTCACAACACGGTGGCAAACAGCGAAATCCCTTTCATGCAGGATGTGACCCGAAGTATCTAGCGTGTCAGCACACCTAAAAACGGAATATCTACGTAGTATTTTCAATCCGTACTTGGAGAGCGAGGGTACACCTCAACTGCGCGCTTAATATAGATGCAATTTGCCGGTACTTACACGGAGAAACAACGTATGAGCGTGAATAGTCTCTTTGTGTTGGCACGTAGTATCAATGGGCAAGTTCAAGTTCTGAGACACCTAGTCTGCATGTTAAACCCTACGACTTCCGCGTCGGAGTAATCAGAAGGACTGAACCATACGGTGGGCCCGTGCCAGTCCTCGGGCCGCGATTCGATCAATGCTGTAGCACATTTTAACCTAGCAAGCTGAGAAACAACTCTCTCCAGTGGCGGGCGTGTCCTGAGGCACATGAATCCGTGATGGGAGTAGCTGTCCCCGCGTATCACATAACTTTTGAATTTTCGCTTACCTCC"

def rna(DNA):

    # Create RNA string from DNA
    u = t.upper().replace("T", "U")

    return u

print(rna(t))
